#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
Bundler.require(:default)

# FIXME: debugging
require "pp"

loader = Zeitwerk::Loader.new
loader.push_dir("lib")
loader.inflector.inflect("cli" => "CLI")
loader.inflector.inflect("hcp_packer" => "HCPPacker")
loader.setup
loader.eager_load

module HCPPacker
  module CLI
    extend Dry::CLI::Registry

    register "auth", Auth
    register "list-buckets", ListBuckets
    register "list-channels", ListChannels
    register "list-iterations", ListIterations
  end
end

Dry::CLI.new(HCPPacker::CLI).call
